// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package moe_dempa_hosting

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	YourName             string   `protobuf:"bytes,1,opt,name=your_name,json=yourName,proto3" json:"your_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetYourName() string {
	if m != nil {
		return m.YourName
	}
	return ""
}

type HelloResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CreateProjectRequest struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectRequest) Reset()         { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()    {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *CreateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectRequest.Unmarshal(m, b)
}
func (m *CreateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectRequest.Merge(m, src)
}
func (m *CreateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProjectRequest.Size(m)
}
func (m *CreateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectRequest proto.InternalMessageInfo

func (m *CreateProjectRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type CreateProjectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectResponse) Reset()         { *m = CreateProjectResponse{} }
func (m *CreateProjectResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProjectResponse) ProtoMessage()    {}
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *CreateProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectResponse.Unmarshal(m, b)
}
func (m *CreateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectResponse.Marshal(b, m, deterministic)
}
func (m *CreateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectResponse.Merge(m, src)
}
func (m *CreateProjectResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProjectResponse.Size(m)
}
func (m *CreateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectResponse proto.InternalMessageInfo

type CreateRevisionRequest struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRevisionRequest) Reset()         { *m = CreateRevisionRequest{} }
func (m *CreateRevisionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRevisionRequest) ProtoMessage()    {}
func (*CreateRevisionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *CreateRevisionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRevisionRequest.Unmarshal(m, b)
}
func (m *CreateRevisionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRevisionRequest.Marshal(b, m, deterministic)
}
func (m *CreateRevisionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRevisionRequest.Merge(m, src)
}
func (m *CreateRevisionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRevisionRequest.Size(m)
}
func (m *CreateRevisionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRevisionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRevisionRequest proto.InternalMessageInfo

func (m *CreateRevisionRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type CreateRevisionResponse struct {
	RevisionId           string   `protobuf:"bytes,1,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRevisionResponse) Reset()         { *m = CreateRevisionResponse{} }
func (m *CreateRevisionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRevisionResponse) ProtoMessage()    {}
func (*CreateRevisionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *CreateRevisionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRevisionResponse.Unmarshal(m, b)
}
func (m *CreateRevisionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRevisionResponse.Marshal(b, m, deterministic)
}
func (m *CreateRevisionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRevisionResponse.Merge(m, src)
}
func (m *CreateRevisionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRevisionResponse.Size(m)
}
func (m *CreateRevisionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRevisionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRevisionResponse proto.InternalMessageInfo

func (m *CreateRevisionResponse) GetRevisionId() string {
	if m != nil {
		return m.RevisionId
	}
	return ""
}

type PutFileRequest struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	RevisionId           string   `protobuf:"bytes,2,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	FilePath             string   `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	TotalFileSize        int32    `protobuf:"varint,4,opt,name=total_file_size,json=totalFileSize,proto3" json:"total_file_size,omitempty"`
	Chunk                []byte   `protobuf:"bytes,5,opt,name=chunk,proto3" json:"chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutFileRequest) Reset()         { *m = PutFileRequest{} }
func (m *PutFileRequest) String() string { return proto.CompactTextString(m) }
func (*PutFileRequest) ProtoMessage()    {}
func (*PutFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *PutFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutFileRequest.Unmarshal(m, b)
}
func (m *PutFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutFileRequest.Marshal(b, m, deterministic)
}
func (m *PutFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutFileRequest.Merge(m, src)
}
func (m *PutFileRequest) XXX_Size() int {
	return xxx_messageInfo_PutFileRequest.Size(m)
}
func (m *PutFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutFileRequest proto.InternalMessageInfo

func (m *PutFileRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *PutFileRequest) GetRevisionId() string {
	if m != nil {
		return m.RevisionId
	}
	return ""
}

func (m *PutFileRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *PutFileRequest) GetTotalFileSize() int32 {
	if m != nil {
		return m.TotalFileSize
	}
	return 0
}

func (m *PutFileRequest) GetChunk() []byte {
	if m != nil {
		return m.Chunk
	}
	return nil
}

type PutFileResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutFileResponse) Reset()         { *m = PutFileResponse{} }
func (m *PutFileResponse) String() string { return proto.CompactTextString(m) }
func (*PutFileResponse) ProtoMessage()    {}
func (*PutFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *PutFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutFileResponse.Unmarshal(m, b)
}
func (m *PutFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutFileResponse.Marshal(b, m, deterministic)
}
func (m *PutFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutFileResponse.Merge(m, src)
}
func (m *PutFileResponse) XXX_Size() int {
	return xxx_messageInfo_PutFileResponse.Size(m)
}
func (m *PutFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutFileResponse proto.InternalMessageInfo

type RevisionCloseRequest struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	RevisionId           string   `protobuf:"bytes,2,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	Publish              bool     `protobuf:"varint,3,opt,name=publish,proto3" json:"publish,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevisionCloseRequest) Reset()         { *m = RevisionCloseRequest{} }
func (m *RevisionCloseRequest) String() string { return proto.CompactTextString(m) }
func (*RevisionCloseRequest) ProtoMessage()    {}
func (*RevisionCloseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *RevisionCloseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevisionCloseRequest.Unmarshal(m, b)
}
func (m *RevisionCloseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevisionCloseRequest.Marshal(b, m, deterministic)
}
func (m *RevisionCloseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevisionCloseRequest.Merge(m, src)
}
func (m *RevisionCloseRequest) XXX_Size() int {
	return xxx_messageInfo_RevisionCloseRequest.Size(m)
}
func (m *RevisionCloseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevisionCloseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevisionCloseRequest proto.InternalMessageInfo

func (m *RevisionCloseRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *RevisionCloseRequest) GetRevisionId() string {
	if m != nil {
		return m.RevisionId
	}
	return ""
}

func (m *RevisionCloseRequest) GetPublish() bool {
	if m != nil {
		return m.Publish
	}
	return false
}

type RevisionCloseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevisionCloseResponse) Reset()         { *m = RevisionCloseResponse{} }
func (m *RevisionCloseResponse) String() string { return proto.CompactTextString(m) }
func (*RevisionCloseResponse) ProtoMessage()    {}
func (*RevisionCloseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *RevisionCloseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevisionCloseResponse.Unmarshal(m, b)
}
func (m *RevisionCloseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevisionCloseResponse.Marshal(b, m, deterministic)
}
func (m *RevisionCloseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevisionCloseResponse.Merge(m, src)
}
func (m *RevisionCloseResponse) XXX_Size() int {
	return xxx_messageInfo_RevisionCloseResponse.Size(m)
}
func (m *RevisionCloseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevisionCloseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevisionCloseResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*HelloRequest)(nil), "moe.dempa.hosting.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "moe.dempa.hosting.HelloResponse")
	proto.RegisterType((*CreateProjectRequest)(nil), "moe.dempa.hosting.CreateProjectRequest")
	proto.RegisterType((*CreateProjectResponse)(nil), "moe.dempa.hosting.CreateProjectResponse")
	proto.RegisterType((*CreateRevisionRequest)(nil), "moe.dempa.hosting.CreateRevisionRequest")
	proto.RegisterType((*CreateRevisionResponse)(nil), "moe.dempa.hosting.CreateRevisionResponse")
	proto.RegisterType((*PutFileRequest)(nil), "moe.dempa.hosting.PutFileRequest")
	proto.RegisterType((*PutFileResponse)(nil), "moe.dempa.hosting.PutFileResponse")
	proto.RegisterType((*RevisionCloseRequest)(nil), "moe.dempa.hosting.RevisionCloseRequest")
	proto.RegisterType((*RevisionCloseResponse)(nil), "moe.dempa.hosting.RevisionCloseResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 542 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6e, 0xd3, 0x40,
	0x14, 0xae, 0x5b, 0x42, 0x9b, 0xd7, 0xa6, 0x55, 0x46, 0x01, 0x2c, 0x03, 0x4a, 0xf0, 0x02, 0x52,
	0x41, 0x6c, 0x01, 0xa2, 0x12, 0xeb, 0x4a, 0xa8, 0xdd, 0xa0, 0xc8, 0x65, 0x8b, 0xa2, 0x89, 0xfd,
	0x6a, 0x0f, 0xb5, 0x3d, 0x83, 0x67, 0x9c, 0x88, 0x2e, 0xb9, 0x02, 0xc7, 0xe0, 0x38, 0x5c, 0x81,
	0x4b, 0xb0, 0x43, 0xb6, 0xc7, 0x81, 0x18, 0x17, 0xb2, 0x60, 0x95, 0xcc, 0x9b, 0xef, 0xfb, 0xde,
	0xdf, 0x37, 0x86, 0x9e, 0xc4, 0x6c, 0xc1, 0x7c, 0x74, 0x44, 0xc6, 0x15, 0x27, 0xfd, 0x84, 0xa3,
	0x13, 0x60, 0x22, 0xa8, 0x13, 0x71, 0xa9, 0x58, 0x1a, 0x5a, 0x0f, 0x42, 0xce, 0xc3, 0x18, 0x5d,
	0x2a, 0x98, 0x4b, 0xd3, 0x94, 0x2b, 0xaa, 0x18, 0x4f, 0x65, 0x45, 0xb0, 0x86, 0xfa, 0xb6, 0x3c,
	0xcd, 0xf3, 0x4b, 0x57, 0xb1, 0x04, 0xa5, 0xa2, 0x89, 0xd0, 0x80, 0x67, 0xe5, 0x8f, 0x3f, 0x09,
	0x31, 0x9d, 0xc8, 0x25, 0x0d, 0x43, 0xcc, 0x5c, 0x2e, 0x4a, 0x89, 0x16, 0xb9, 0x93, 0x90, 0xa9,
	0x28, 0x9f, 0x3b, 0x3e, 0x4f, 0xdc, 0x64, 0xc9, 0xd4, 0x15, 0x5f, 0xba, 0x21, 0x9f, 0x94, 0x97,
	0x93, 0x05, 0x8d, 0x59, 0x40, 0x15, 0xcf, 0xa4, 0xbb, 0xfa, 0x5b, 0xf1, 0xec, 0xa7, 0x70, 0x70,
	0x86, 0x71, 0xcc, 0x3d, 0xfc, 0x98, 0xa3, 0x54, 0xe4, 0x3e, 0x74, 0x3f, 0xf1, 0x3c, 0x9b, 0xa5,
	0x34, 0x41, 0xd3, 0x18, 0x19, 0xe3, 0xae, 0xb7, 0x57, 0x04, 0xde, 0xd2, 0x04, 0xed, 0x63, 0xe8,
	0x69, 0xb0, 0x14, 0x3c, 0x95, 0x48, 0x4c, 0xd8, 0x4d, 0x50, 0x4a, 0x1a, 0xd6, 0xd8, 0xfa, 0x68,
	0xbf, 0x82, 0xc1, 0x69, 0x86, 0x54, 0xe1, 0x34, 0xe3, 0x1f, 0xd0, 0x57, 0xb5, 0xfe, 0x43, 0x00,
	0x51, 0x45, 0x66, 0x2c, 0xd0, 0xa4, 0xae, 0x8e, 0x9c, 0x07, 0xf6, 0x3d, 0xb8, 0xd3, 0xa0, 0x55,
	0x99, 0xec, 0x93, 0xfa, 0xc2, 0xc3, 0x05, 0x93, 0x8c, 0xa7, 0x1b, 0x0a, 0xbe, 0x86, 0xbb, 0x4d,
	0x9e, 0xae, 0x7d, 0x08, 0xfb, 0x99, 0x8e, 0xfd, 0x62, 0x42, 0x1d, 0x3a, 0x0f, 0xec, 0xaf, 0x06,
	0x1c, 0x4e, 0x73, 0xf5, 0x86, 0xc5, 0xb8, 0x59, 0xb2, 0xa6, 0xe4, 0x76, 0x53, 0xb2, 0x98, 0xee,
	0x25, 0x8b, 0x71, 0x26, 0xa8, 0x8a, 0xcc, 0x9d, 0x6a, 0xba, 0x45, 0x60, 0x4a, 0x55, 0x44, 0x1e,
	0xc3, 0x91, 0xe2, 0x8a, 0xc6, 0xb3, 0x12, 0x22, 0xd9, 0x35, 0x9a, 0xb7, 0x46, 0xc6, 0xb8, 0xe3,
	0xf5, 0xca, 0x70, 0x51, 0xc7, 0x05, 0xbb, 0x46, 0x32, 0x80, 0x8e, 0x1f, 0xe5, 0xe9, 0x95, 0xd9,
	0x19, 0x19, 0xe3, 0x03, 0xaf, 0x3a, 0xd8, 0x7d, 0x38, 0x5a, 0x15, 0xab, 0x67, 0x26, 0x60, 0x50,
	0x77, 0x7d, 0x1a, 0x73, 0xf9, 0xdf, 0xba, 0x30, 0x61, 0x57, 0xe4, 0xf3, 0x98, 0xc9, 0xaa, 0x87,
	0x3d, 0xaf, 0x3e, 0x16, 0xeb, 0x6b, 0x64, 0xac, 0x4a, 0x79, 0xf1, 0x63, 0x07, 0x7a, 0x17, 0x85,
	0x63, 0xfd, 0xb3, 0xea, 0x75, 0x90, 0xf7, 0xd0, 0x29, 0xbd, 0x44, 0x86, 0xce, 0x1f, 0x4f, 0xc7,
	0xf9, 0xdd, 0x92, 0xd6, 0xe8, 0x66, 0x80, 0x6e, 0xb4, 0xff, 0xf9, 0xdb, 0xf7, 0x2f, 0xdb, 0xfb,
	0xa4, 0xeb, 0x2e, 0x9e, 0xbb, 0x51, 0xa9, 0x1a, 0x40, 0x6f, 0xcd, 0x48, 0xe4, 0x49, 0x8b, 0x4a,
	0x9b, 0x43, 0xad, 0xf1, 0xbf, 0x81, 0x3a, 0xed, 0x16, 0x09, 0xe1, 0x70, 0xdd, 0x5d, 0xe4, 0x66,
	0x76, 0xc3, 0xb8, 0xd6, 0xf1, 0x06, 0xc8, 0x55, 0xa2, 0x77, 0xb0, 0xab, 0xb7, 0x4b, 0x1e, 0xb5,
	0xf0, 0xd6, 0x6d, 0x6a, 0xd9, 0x7f, 0x83, 0xd4, 0x9a, 0x63, 0xa3, 0x18, 0xd2, 0xda, 0xba, 0x5a,
	0x87, 0xd4, 0x66, 0xa1, 0xd6, 0x21, 0xb5, 0x6e, 0xde, 0xde, 0x9a, 0xdf, 0x2e, 0xbf, 0x34, 0x2f,
	0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x36, 0xd1, 0xe2, 0xfd, 0x32, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StaticHostingClient is the client API for StaticHosting service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StaticHostingClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error)
	CreateRevision(ctx context.Context, in *CreateRevisionRequest, opts ...grpc.CallOption) (*CreateRevisionResponse, error)
	PutFile(ctx context.Context, opts ...grpc.CallOption) (StaticHosting_PutFileClient, error)
	RevisionClose(ctx context.Context, in *RevisionCloseRequest, opts ...grpc.CallOption) (*RevisionCloseResponse, error)
}

type staticHostingClient struct {
	cc *grpc.ClientConn
}

func NewStaticHostingClient(cc *grpc.ClientConn) StaticHostingClient {
	return &staticHostingClient{cc}
}

func (c *staticHostingClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/moe.dempa.hosting.StaticHosting/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticHostingClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error) {
	out := new(CreateProjectResponse)
	err := c.cc.Invoke(ctx, "/moe.dempa.hosting.StaticHosting/CreateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticHostingClient) CreateRevision(ctx context.Context, in *CreateRevisionRequest, opts ...grpc.CallOption) (*CreateRevisionResponse, error) {
	out := new(CreateRevisionResponse)
	err := c.cc.Invoke(ctx, "/moe.dempa.hosting.StaticHosting/CreateRevision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticHostingClient) PutFile(ctx context.Context, opts ...grpc.CallOption) (StaticHosting_PutFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StaticHosting_serviceDesc.Streams[0], "/moe.dempa.hosting.StaticHosting/PutFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &staticHostingPutFileClient{stream}
	return x, nil
}

type StaticHosting_PutFileClient interface {
	Send(*PutFileRequest) error
	CloseAndRecv() (*PutFileResponse, error)
	grpc.ClientStream
}

type staticHostingPutFileClient struct {
	grpc.ClientStream
}

func (x *staticHostingPutFileClient) Send(m *PutFileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *staticHostingPutFileClient) CloseAndRecv() (*PutFileResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PutFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *staticHostingClient) RevisionClose(ctx context.Context, in *RevisionCloseRequest, opts ...grpc.CallOption) (*RevisionCloseResponse, error) {
	out := new(RevisionCloseResponse)
	err := c.cc.Invoke(ctx, "/moe.dempa.hosting.StaticHosting/RevisionClose", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StaticHostingServer is the server API for StaticHosting service.
type StaticHostingServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error)
	CreateRevision(context.Context, *CreateRevisionRequest) (*CreateRevisionResponse, error)
	PutFile(StaticHosting_PutFileServer) error
	RevisionClose(context.Context, *RevisionCloseRequest) (*RevisionCloseResponse, error)
}

// UnimplementedStaticHostingServer can be embedded to have forward compatible implementations.
type UnimplementedStaticHostingServer struct {
}

func (*UnimplementedStaticHostingServer) Hello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (*UnimplementedStaticHostingServer) CreateProject(ctx context.Context, req *CreateProjectRequest) (*CreateProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProject not implemented")
}
func (*UnimplementedStaticHostingServer) CreateRevision(ctx context.Context, req *CreateRevisionRequest) (*CreateRevisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRevision not implemented")
}
func (*UnimplementedStaticHostingServer) PutFile(srv StaticHosting_PutFileServer) error {
	return status.Errorf(codes.Unimplemented, "method PutFile not implemented")
}
func (*UnimplementedStaticHostingServer) RevisionClose(ctx context.Context, req *RevisionCloseRequest) (*RevisionCloseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevisionClose not implemented")
}

func RegisterStaticHostingServer(s *grpc.Server, srv StaticHostingServer) {
	s.RegisterService(&_StaticHosting_serviceDesc, srv)
}

func _StaticHosting_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticHostingServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moe.dempa.hosting.StaticHosting/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticHostingServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaticHosting_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticHostingServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moe.dempa.hosting.StaticHosting/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticHostingServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaticHosting_CreateRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticHostingServer).CreateRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moe.dempa.hosting.StaticHosting/CreateRevision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticHostingServer).CreateRevision(ctx, req.(*CreateRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaticHosting_PutFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StaticHostingServer).PutFile(&staticHostingPutFileServer{stream})
}

type StaticHosting_PutFileServer interface {
	SendAndClose(*PutFileResponse) error
	Recv() (*PutFileRequest, error)
	grpc.ServerStream
}

type staticHostingPutFileServer struct {
	grpc.ServerStream
}

func (x *staticHostingPutFileServer) SendAndClose(m *PutFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *staticHostingPutFileServer) Recv() (*PutFileRequest, error) {
	m := new(PutFileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StaticHosting_RevisionClose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevisionCloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticHostingServer).RevisionClose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moe.dempa.hosting.StaticHosting/RevisionClose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticHostingServer).RevisionClose(ctx, req.(*RevisionCloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StaticHosting_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moe.dempa.hosting.StaticHosting",
	HandlerType: (*StaticHostingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _StaticHosting_Hello_Handler,
		},
		{
			MethodName: "CreateProject",
			Handler:    _StaticHosting_CreateProject_Handler,
		},
		{
			MethodName: "CreateRevision",
			Handler:    _StaticHosting_CreateRevision_Handler,
		},
		{
			MethodName: "RevisionClose",
			Handler:    _StaticHosting_RevisionClose_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PutFile",
			Handler:       _StaticHosting_PutFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
